services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  rustfs:
    restart: always
    image: rustfs/rustfs:1.0.1
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  rustfs-setup:
    image: amazon/aws-cli
    depends_on:
      rustfs:
        condition: service_healthy
    volumes:
      - ./rustfs/create-bucket.sh:/create-bucket.sh
    entrypoint: /bin/sh
    command: -c "chmod +x /create-bucket.sh && /create-bucket.sh"
    environment:
      - AWS_ACCESS_KEY_ID=${RUSTFS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${RUSTFS_SECRET_KEY}
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=${MLFLOW_S3_ENDPOINT}

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "5001:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${RUSTFS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${RUSTFS_SECRET_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT}
      - MLFLOW_S3_IGNORE_TLS=true
      # Allowed hosts required > v3.5 mlflow
      # https://mlflow.org/docs/latest/self-hosting/security/network
      - MLFLOW_SERVER_ALLOWED_HOSTS=${MLFLOW_SERVER_ALLOWED_HOSTS}
      - MLFLOW_SERVER_CORS_ALLOWED_ORIGINS=${MLFLOW_SERVER_CORS_ALLOWED_ORIGINS}

    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/mlflow
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://mlflow
      --allowed-hosts ${MLFLOW_SERVER_ALLOWED_HOSTS}
      --cors-allowed-origins ${MLFLOW_SERVER_CORS_ALLOWED_ORIGINS}
    depends_on:
      postgres:
        condition: service_started
      rustfs-setup:
        condition: service_completed_successfully


volumes:
  postgres_data:
  rustfs_data:
